import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Ball: NextPage = () => {
    return (
        <>
        <Head>
            <title>Ball</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Link href="/sports">Go to sports</Link>
        </>
    );
};


export default Ball;