import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Counter from "../components/counter"

const Sports: NextPage = () => {
    return (
        <>
            <Head>
                <title>Sports</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link className="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded"
                href="/ball">Go to ball
            </Link>
            <Counter/>
        </>
    )
}

export default Sports;